# Generated by Django 5.0.6 on 2024-08-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipesuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipesuser'),
        ),
        migrations.AlterField(
            model_name='recipesuser',
            name='gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
